// src/mockData.js

export const mockRawData = [
    {
        "NO.": 1,
        "TANGGAL": "17/05/2025 19:47",
        "NO REG": 2505020620,
        "NO RM": 7382914,
        "NAMA PASIEN": "Nadia Putri",
        "Jenis Kelamin": "Perempuan",
        "Usia": 24,
        "Tgl Lahir": "03/07/2000",
        "Unit Kerja": "Instalasi Radiologi",
        "Jabatan": "Perawat Terampil",
        "Ketenagaan": "Tenaga Kesehatan",
        "Tanggal Periksa": "02/04/2025",
        "BB\n(Kg)": 60,
        "TB\n(Cm)": 159,
        "IMT": 23.73,
        "Kategori IMT": "Normal",
        "TD": "100/71",
        "Kategori TD": "Optimal",
        "Riwayat Kesehatan Pribadi": "Riwayat Penyakit : Tidak Ada, Riwayat Operasi : Sectio Caesaria 2020 di RS Haji, Riwayat Alergi : Tidak Ada",
        "Riwayat Kesehatan Keluarga": "Riwayat Penyakit Keluarga : Tidak Ada",
        "Anamnesa": "Anamnesa : Keluhan saat ini : Sedang Hamil G2P1A0 H 28 minggu",
        "Merokok": "Tidak",
        "Alkohol": "Tidak",
        "Olahraga": "",
        "EKG": "normal",
        "Kreatinin": 0.6,
        "Egfr": 125,
        "Ureum": 15,
        "Glukosa Puasa": 79.0,
        "Anti Hbs": "",
        "Hbsag": "",
        "Asam Urat": 4.5,
        "Basofil": 0.2,
        "Eosinofil": 1.1,
        "Hb": 11.6,
        "Hematokrit": 35.1,
        "Trombosit": 283,
        "Eritrosit": 5.11,
        "Lekosit": 9.28,
        "Mch": 22.7,
        "Mchc": 33.0,
        "Mcv": 68.8,
        "Limfosit": 14.8,
        "Monosit": 5.7,
        "Neutrofil": 78.2,
        "Neutrofil Limfosit Ratio": 5.28,
        "Rdw-Cv": 14.5,
        "Koles Hdl": 61,
        "Koles Ldl": 147,
        "Trigliserid": 170,
        "Sgot": 18,
        "Sgpt": 11,
        "Kolesterol": "233 Borderline", // Example of string format
        "Ph": 7.0,
        "Warna": "Kuning Muda",
        "Kejernihan": "Jernih",
        "Leukosit": 66.4,
        "Eritosit": 1.20,
        "Epitel": 65.80,
        "Bakteri": 2183.80,
        "Silinder": 0.00,
        "Kristal": 0.0,
        "Berat Jenis": 1.010,
        "Protein": "Negatif",
        "Glukosa": "Negatif",
        "Keton": "Negatif",
        "Darah": "Negatif",
        "Bilirubin": "Negatif",
        "Urobilinogen": "Normal",
        "Nitrit": "Negatif",
        "Lekosit Esteras": "2+",
        "Rasio Albumin Kreatinin": "< 30",
        "Laboratorium": "Kolesterol Total 233 mg/dL, Kolesterol LDL 147 mg/dL, Laju Endap Darah 35 mm, Hemoglobin 11.6 g/dL, Eritrosit 5.11 10^6/ÂµL, Trigliserida 170 mg/dL, Urine: Leukosit 66.4 /ÂµL, Sel Epitel 65.80 /ÂµL, Bakteria 2183.80 /ÂµL, Leukosit Esterase 2+ (Kolesterol Total meningkat, LDL meningkat, LED meningkat, Anemia ringan, Eritrositosis, Trigliserida meningkat, Leukosituria, Bakteriuria suspek infeksi saluran kemih)",
        "Pemeriksaan Hepatitis": null,
        "Audiometri": null,
        "Radiologi": " Sedang hamil 28 minggu",
        "Fisik": "BMI : Overweight [28,12] (sedang hamil 28 minggu), TD : Optimal",
        "Visus": " Mata Kanan : 6/6, Mata Kiri : 6/6",
        "Buta Warna": "Tidak",
        "Saran": "Fisik : Kontrol dr. Sp. OG secara berkala, EKG : null, Visus : ---, Laboratorium : Istirahat cukup, minum air putih cukup, diet rendah lemak jenuh, konsumsi makanan berzat besi konsul dr. Sp. PD, Audiometri : null, Rontgen Thorax : ---, Buta Warna : ---"
    },
    {
        "NO.": 2,
        "TANGGAL": "17/05/2025 20:01",
        "NO REG": 2505020623,
        "NO RM": 1049275,
        "NAMA PASIEN": "Intan Ayu Les",
        "Jenis Kelamin": "Perempuan",
        "Usia": 31,
        "Tgl Lahir": "15/10/1993",
        "Unit Kerja": "Instalasi Radiologi",
        "Jabatan": "Terampil Radiografer",
        "Ketenagaan": "Tenaga Kesehatan",
        "Tanggal Periksa": "02/04/2025",
        "BB\n(Kg)": 63,
        "TB\n(Cm)": 155,
        "IMT": 26.22,
        "Kategori IMT": "Overweight",
        "TD": "107/68",
        "Kategori TD": "Optimal",
        "Riwayat Kesehatan Pribadi": "Riwayat Penyakit : Dyspepsia",
        "Riwayat Kesehatan Keluarga": "Riwayat Penyakit Keluarga : Diabetes",
        "Anamnesa": "Anamnesa : Keluhan saat ini : --",
        "Merokok": "Tidak",
        "Alkohol": "Tidak",
        "Olahraga": "",
        "EKG": "Sinus",
        "Kreatinin": 0.7,
        "Egfr": 107,
        "Ureum": 18,
        "Glukosa Puasa": 81.0,
        "Anti Hbs": "",
        "Hbsag": "",
        "Asam Urat": 5.1, // Nilai asam urat untuk perempuan biasanya lebih rendah
        "Basofil": 0.5,
        "Eosinofil": 2.5,
        "Hb": 14.1, // Normal Hb for woman
        "Hematokrit": 42.7,
        "Trombosit": 352,
        "Eritrosit": 4.75,
        "Lekosit": 7.51,
        "Mch": 29.6,
        "Mchc": 33.0,
        "Mcv": 89.8,
        "Limfosit": 44.3,
        "Monosit": 6.0,
        "Neutrofil": 46.7,
        "Neutrofil Limfosit Ratio": 1.05,
        "Rdw-Cv": 13.5,
        "Koles Hdl": 58, // Normal HDL for woman
        "Koles Ldl": 130, // Borderline LDL
        "Trigliserid": 54, // Normal Trigliserida
        "Sgot": 19, // Normal SGOT
        "Sgpt": 10, // Normal SGPT
        "Kolesterol": "198 Optima", // Example of string format
        "Ph": 5.0,
        "Warna": "Kuning Pucat",
        "Kejernihan": "Jernih",
        "Leukosit": 31.6,
        "Eritrosit": 3.30,
        "Epitel": 14.80,
        "Bakteri": 957.50,
        "Silinder": 0.13,
        "Kristal": 0.0,
        "Berat Jenis": 1.024,
        "Protein": "Negatif",
        "Glukosa": "Negatif",
        "Keton": "Negatif",
        "Darah": "Negatif",
        "Bilirubin": "Negatif",
        "Urobilinogen": "Normal",
        "Nitrit": "Negatif",
        "Lekosit Esteras": "2+",
        "Rasio Albumin Kreatinin": "< 30",
        "Laboratorium": "Kolesterol Total 198 mg/dL, Kolesterol LDL 130 mg/dL, Trigliserida 54 mg/dL",
        "Pemeriksaan Hepatitis": null,
        "Audiometri": null,
        "Radiologi": "Cor, pulmo, sinus",
        "Fisik": "BMI: Overweight",
        "Visus": " Mata Kanan : 6/6, Mata Kiri : 6/6",
        "Buta Warna": "Tidak",
        "Saran": "Fisik : Kontrol dr. Sp. PD/Sp. OG, EKG : null, Visus : ---, Laboratorium : Edukasi pola hidup sehat (konsumsi makanan rendah lemak jenuh, olahraga teratur), Audiometri : null, Rontgen Thorax : ---, Buta Warna : ---"
    },
     {
        "NO.": 3,
        "TANGGAL": "17/05/2025 20:25",
        "NO REG": 2505020630,
        "NO RM": 8927346,
        "NAMA PASIEN": "Andi Pratama",
        "Jenis Kelamin": "Laki-laki",
        "Usia": 26,
        "Tgl Lahir": "08/02/1999",
        "Unit Kerja": "Instalasi Radiologi",
        "Jabatan": "Terampil Radiografer",
        "Ketenagaan": "Tenaga Kesehatan",
        "Tanggal Periksa": "04/04/2025",
        "BB\n(Kg)": 72,
        "TB\n(Cm)": 175,
        "IMT": 23.51,
        "Kategori IMT": "Normal",
        "TD": "120/74",
        "Kategori TD": "Normal", // S=120, D=74 -> Normal based on sample
        "Riwayat Kesehatan Pribadi": "Riwayat Penyakit : Tidak Ada",
        "Riwayat Kesehatan Keluarga": "Riwayat Penyakit Keluarga : Tidak Ada",
        "Anamnesa": "Anamnesa : Keluhan saat ini : --",
        "Merokok": "Tidak",
        "Alkohol": "Tidak",
        "Olahraga": "",
        "EKG": "Sinus Rhytm Normal",
        "Kreatinin": 0.9, // Normal
        "Egfr": 105,
        "Ureum": 16, // Normal
        "Glukosa Puasa": 82.0, // Normal
        "Anti Hbs": "",
        "Hbsag": "",
        "Asam Urat": 6.4, // Normal for man < 7.0
        "Basofil": 0.9,
        "Eosinofil": 2.2,
        "Hb": 14.7, // Normal for man
        "Hematokrit": 45.4,
        "Trombosit": 315,
        "Eritrosit": 5.92,
        "Lekosit": 5.77,
        "Mch": 24.9,
        "Mchc": 32.4,
        "Mcv": 76.7,
        "Limfosit": 44.9,
        "Monosit": 7.7,
        "Neutrofil": 44.3,
        "Neutrofil Limfosit Ratio": 0.99,
        "Rdw-Cv": 14.3,
        "Koles Hdl": 48, // Normal
        "Koles Ldl": 130, // Borderline
        "Trigliserid": 77, // Normal
        "Sgot": 18, // Normal
        "Sgpt": 13, // Normal
        "Kolesterol": "192 Optima", // Example of string format
        "Ph": 5.5,
        "Warna": "Kuning Pucat",
        "Kejernihan": "Jernih",
        "Leukosit": 0.7,
        "Eritrosit": 3.30,
        "Epitel": 0.40,
        "Bakteri": 135.40,
        "Silinder": 0.00,
        "Kristal": 0.0,
        "Berat Jenis": 1.022,
        "Protein": "Negatif",
        "Glukosa": "Negatif",
        "Keton": "Negatif",
        "Darah": "Negatif",
        "Bilirubin": "Negatif",
        "Urobilinogen": "Normal",
        "Nitrit": "Negatif",
        "Lekosit Esteras": "Negatif",
        "Rasio Albumin Kreatinin": "< 30",
        "Laboratorium": "Kolesterol Total 192 mg/dL, Kolesterol LDL 130 mg/dL, Trigliserida 77 mg/dL",
        "Pemeriksaan Hepatitis": null,
        "Audiometri": null,
        "Radiologi": "Cor, pulmo, sinus",
        "Fisik": "BMI: Normal",
        "Visus": " Mata Kanan : 6/7.5 Mata Kiri : 6/7.5",
        "Buta Warna": "Tidak",
        "Saran": "Fisik : ---, EKG : null, Visus : Turunkan minus/plus (konsul dr. Sp. M), Laboratorium : Edukasi pola hidup sehat (konsumsi makanan rendah lemak jenuh, olahraga teratur), Audiometri : null, Rontgen Thorax : ---, Buta Warna : ---"
    },
    {
        "NO.": 4,
        "TANGGAL": "17/05/2025 21:30",
        "NO REG": 2505021234,
        "NO RM": 5601823,
        "NAMA PASIEN": "Joko Rahmat",
        "Jenis Kelamin": "Laki-laki",
        "Usia": 28,
        "Tgl Lahir": "22/03/1997",
        "Unit Kerja": "Instalasi Radiologi",
        "Jabatan": "Terampil Radiografer",
        "Ketenagaan": "Tenaga Kesehatan Fisikawan",
        "Tanggal Periksa": "04/04/2025",
        "BB\n(Kg)": 52,
        "TB\n(Cm)": 153,
        "IMT": 22.21,
        "Kategori IMT": "Normal",
        "TD": "96/66",
        "Kategori TD": "Normal", // S=96, D=66 -> Normal based on sample
        "Riwayat Kesehatan Pribadi": "Riwayat Penyakit : Tidak Ada",
        "Riwayat Kesehatan Keluarga": "Riwayat Penyakit Keluarga : Tidak Ada",
        "Anamnesa": "Anamnesa : Keluhan saat ini : --",
        "Merokok": "Tidak",
        "Alkohol": "Tidak",
        "Olahraga": "",
        "EKG": "Sinus",
        "Kreatinin": 0.8, // Normal
        "Egfr": 94,
        "Ureum": 20, // Normal
        "Glukosa Puasa": 84.0, // Normal
        "Anti Hbs": "",
        "Hbsag": "",
        "Asam Urat": 3.7, // Normal for man
        "Basofil": 0.3,
        "Eosinofil": 2.4,
        "Hb": 13.6, // Normal for man
        "Hematokrit": 41.6,
        "Trombosit": 275,
        "Eritrosit": 4.67,
        "Lekosit": 7.78,
        "Mch": 29.2,
        "Mchc": 32.8,
        "Mcv": 89.1,
        "Limfosit": 33.9,
        "Monosit": 6.4,
        "Neutrofil": 57.0,
        "Neutrofil Limfosit Ratio": 1.68,
        "Rdw-Cv": 13.5,
        "Koles Hdl": 65, // Normal
        "Koles Ldl": 116, // Hampir Optimal
        "Trigliserid": 40, // Normal
        "Sgot": 16, // Normal
        "Sgpt": 9, // Normal
        "Kolesterol": "196 Optima", // Example of string format
        "Ph": 7.0,
        "Warna": "Kuning Muda",
        "Kejernihan": "Jernih",
        "Leukosit": 6.3,
        "Eritrosit": 1.10,
        "Epitel": 15.50,
        "Bakteri": 175.70,
        "Silinder": 0.00,
        "Kristal": 0.0,
        "Berat Jenis": 1.017,
        "Protein": "Negatif",
        "Glukosa": "Negatif",
        "Keton": "Negatif",
        "Darah": "Negatif",
        "Bilirubin": "Negatif",
        "Urobilinogen": "Normal",
        "Nitrit": "Negatif",
        "Lekosit Esteras": "Negatif",
        "Rasio Albumin Kreatinin": "< 30",
        "Laboratorium": "Kolesterol Total 196 mg/dL, Kolesterol LDL 116 mg/dL, Trigliserida 40 mg/dL",
        "Pemeriksaan Hepatitis": null,
        "Audiometri": null,
        "Radiologi": "Cor, pulmo, sinus Radiografi thorax",
        "Fisik": "BMI : Normal",
        "Visus": " Mata Kanan : 6/6, Mata Kiri : 6/6",
        "Buta Warna": "Tidak",
        "Saran": "Fisik : ---, EKG : null, Visus : ---, Laboratorium : Edukasi pola hidup sehat (konsumsi makanan rendah lemak jenuh, olahraga teratur), Audiometri : null, Rontgen Thorax : ---, Buta Warna : ---"
    },
     {
        "NO.": 5,
        "TANGGAL": "18/05/2025 08:23",
        "NO REG": 2505030422,
        "NO RM": 7493051,
        "NAMA PASIEN": "Dewi Anindya",
        "Jenis Kelamin": "Perempuan",
        "Usia": 35, // Edge case for >=35
        "Tgl Lahir": "30/11/1989",
        "Unit Kerja": "Instalasi Radiologi",
        "Jabatan": "Perawat",
        "Ketenagaan": "Medis Ahli",
        "Tanggal Periksa": "10/04/2025",
        "BB\n(Kg)": 61,
        "TB\n(Cm)": 149,
        "IMT": 27.48,
        "Kategori IMT": "Overweight",
        "TD": "125/75",
        "Kategori TD": "Normal", // S=125, D=75 -> Normal based on sample
        "Riwayat Kesehatan Pribadi": "Riwayat Penyakit : Asma",
        "Riwayat Kesehatan Keluarga": "Riwayat Penyakit Keluarga : Tidak Ada",
        "Anamnesa": "Anamnesa : Keluhan saat ini : --",
        "Merokok": "Tidak",
        "Alkohol": "Tidak",
        "Olahraga": "",
        "EKG": "Sinus Rhytm",
        "Kreatinin": 0.6, // Normal
        "Egfr": 122,
        "Ureum": 23, // Normal
        "Glukosa Puasa": 105.0, // Normal based on prompt's rule (70-105 inclusive)
        "Anti Hbs": "16.95 Reaktif",
        "Hbsag": "Non Reaktif",
        "Asam Urat": 5.1, // Normal for woman
        "Basofil": 0.3,
        "Eosinofil": 2.7,
        "Hb": 13.2, // Normal for woman
        "Hematokrit": 40.3,
        "Trombosit": 334,
        "Eritrosit": 4.58,
        "Lekosit": 6.29,
        "Mch": 28.8,
        "Mchc": 32.8,
        "Mcv": 87.9,
        "Limfosit": 43.9,
        "Monosit": 7.4,
        "Neutrofil": 45.7,
        "Neutrofil Limfosit Ratio": 1.04,
        "Rdw-Cv": 14.6,
        "Koles Hdl": 44, // Normal
        "Koles Ldl": 138, // Batas Tinggi
        "Trigliserid": 111, // Normal
        "Sgot": 19, // Normal
        "Sgpt": 20, // Normal
        "Kolesterol": "191 Optima",
        "Ph": 5.5,
        "Warna": "Kuning Pucat",
        "Kejernihan": "Jernih",
        "Leukosit": 52.4,
        "Eritrosit": 11.20,
        "Epitel": 16.40,
        "Bakteri": 266.40,
        "Silinder": 0.00,
        "Kristal": 0.0,
        "Berat Jenis": 1.024,
        "Protein": "Negatif",
        "Glukosa": "Negatif",
        "Keton": "Negatif",
        "Darah": "Negatif", // Sample shows '+' here, let's use Negatif for consistency or add '+' to mock
        "Bilirubin": "Negatif",
        "Urobilinogen": "Normal",
        "Nitrit": "Negatif",
        "Lekosit Esteras": "2+",
        "Rasio Albumin Kreatinin": "< 30",
        "Laboratorium": "HDL 44, LDL 138, TRIG 111, SGOT 19, SGPT 20, KOLES 191",
        "Pemeriksaan Hepatitis": "Anti Hbs : Reaktif, HbsAg : Non Reaktif",
        "Audiometri": null,
        "Radiologi": "Radiografi thorax",
        "Fisik": "BMI : Normal", // Sample says Overweight based on BMI 27.48. Typo in sample's Fisik text? Let's trust BMI value.
        "Visus": " Mata Kanan : 6/6, Mata Kiri : 6/6",
        "Buta Warna": "Tidak",
        "Saran": "EKG : null, Visus : ---, Laboratorium : Pemeriksaan Hepatitis B : Vaksinasi Hepatitis B, Audiometri : null, Rontgen Thorax : ---, Buta Warna : ---"
    },
     {
        "NO.": 6,
        "TANGGAL": "18/05/2025 08:25",
        "NO REG": 2551030353,
        "NO RM": 3829176,
        "NAMA PASIEN": "Melati Kusuma",
        "Jenis Kelamin": "Perempuan",
        "Usia": 21, // <35
        "Tgl Lahir": "18/06/2000",
        "Unit Kerja": "Instalasi Rawat Inap",
        "Jabatan": "Kepala KSM",
        "Ketenagaan": "Tenaga Kesehatan",
        "Tanggal Periksa": "10/04/2025",
        "BB\n(Kg)": 61,
        "TB\n(Cm)": 150,
        "IMT": 27.11,
        "Kategori IMT": "Overweight",
        "TD": "106/69",
        "Kategori TD": "Optimal",
        "Riwayat Kesehatan Pribadi": "Riwayat Penyakit : Thypoid",
        "Riwayat Kesehatan Keluarga": "Riwayat Penyakit Keluarga : Tidak Ada",
        "Anamnesa": "Anamnesa : Keluhan saat ini : ---",
        "Merokok": "Tidak",
        "Alkohol": "Tidak",
        "Olahraga": "",
        "EKG": "normal",
        "Kreatinin": 0.6, // Normal
        "Egfr": 112,
        "Ureum": 15, // Normal
        "Glukosa Puasa": 90.0, // Normal
        "Anti Hbs": "0 Non Reaktif", // Example of string parsing needed
        "Hbsag": "7 Non Reaktif", // Example of string parsing needed
        "Asam Urat": 3.8, // Normal for woman
        "Basofil": 0.5,
        "Eosinofil": 2.2,
        "Hb": 9.0, // Anemia for woman
        "Hematokrit": 27.5,
        "Trombosit": 484,
        "Eritrosit": 4.85,
        "Lekosit": 3.44,
        "Mch": 18.6,
        "Mchc": 32.9,
        "Mcv": 56.7,
        "Limfosit": 47.6,
        "Monosit": 7.8,
        "Neutrofil": 41.9,
        "Neutrofil Limfosit Ratio": 0.88,
        "Rdw-Cv": 20.4, // High RDw-Cv
        "Koles Hdl": 30, // Rendah HDL
        "Koles Ldl": 117, // Hampir Optimal
        "Trigliserid": 109, // Normal
        "Sgot": 19, // Normal
        "Sgpt": 13, // Normal
        "Kolesterol": "158 Optima", // Total low? Sample says Optima. Value 158 is Normal per rules.
        "Ph": 5.5,
        "Warna": "Kuning Pucat",
        "Kejernihan": "Jernih",
        "Leukosit": 55.2,
        "Eritrosit": 5.50,
        "Epitel": 13.20,
        "Bakteri": 200.10,
        "Silinder": 0.00,
        "Kristal": 0.0,
        "Berat Jenis": 1.022,
        "Protein": "Negatif",
        "Glukosa": "Negatif",
        "Keton": "Negatif",
        "Darah": "Negatif",
        "Bilirubin": "Negatif",
        "Urobilinogen": "Normal",
        "Nitrit": "Negatif",
        "Lekosit Esteras": "Negatif",
        "Rasio Albumin Kreatinin": "< 30",
        "Laboratorium": "Kolesterol Total 158 mg/dL, Kolesterol LDL 117 mg/dL, Trigliserida 109 mg/dL, Hemoglobin 9.0 g/dL, MCV 56.7 fL, RDW-CV 20.4%",
        "Pemeriksaan Hepatitis": "Anti Hbs : Non Reaktif, HbsAg : Non Reaktif",
        "Audiometri": null,
        "Radiologi": "Cor, pulmo, sinus",
        "Fisik": "BMI: Overweight",
        "Visus": " Mata Kanan : 6/6, Mata Kiri : 6/6",
        "Buta Warna": "Tidak",
        "Saran": "Fisik : ---, EKG : null, Visus : ---, Laboratorium : Istirahat cukup, minum air putih cukup, konsumsi makanan tinggi zat besi konsul dr. Sp. PD (suspek anemia defisiensi besi), Audiometri : null, Rontgen Thorax : ---, Buta Warna : ---"
    },
     {
        "NO.": 7,
        "TANGGAL": "18/05/2025 08:41",
        "NO REG": 2505030739,
        "NO RM": 6192048,
        "NAMA PASIEN": "Rizky Hidayat",
        "Jenis Kelamin": "Laki-laki",
        "Usia": 42, // >=35
        "Tgl Lahir": "01/10/1983",
        "Unit Kerja": "Instalasi Radiologi",
        "Jabatan": "Kepala KSM",
        "Ketenagaan": "Tenaga", // Missing "Kesehatan"? Handle missing data gracefully.
        "Tanggal Periksa": "10/04/2025",
        "BB\n(Kg)": 120,
        "TB\n(Cm)": 189,
        "IMT": 33.59,
        "Kategori IMT": "Obese I",
        "TD": "120/80", // S=120, D=80
        "Kategori TD": "Normal", // Sample says Normal. By rule S<120, D<80 is Optimal. S<130, D<85 is Normal. This fits.
        "Riwayat Kesehatan Pribadi": "Riwayat Penyakit : Hipertensi, Penyakit Jantung",
        "Riwayat Kesehatan Keluarga": "Riwayat Penyakit Keluarga : Hipertensi",
        "Anamnesa": "Anamnesa : Keluhan saat ini : ---",
        "Merokok": "Tidak",
        "Alkohol": "Tidak",
        "Olahraga": "",
        "EKG": "Sinus",
        "Kreatinin": 0.9, // Normal
        "Egfr": 103,
        "Ureum": 22, // Normal
        "Glukosa Puasa": 80.0, // Normal
        "Anti Hbs": "",
        "Hbsag": "",
        "Asam Urat": 4.8, // Normal man
        "Basofil": 0.2,
        "Eosinofil": 2.8,
        "Hb": 14.6, // Normal man
        "Hematokrit": 44.8,
        "Trombosit": 287,
        "Eritrosit": 5.19,
        "Lekosit": 8.12,
        "Mch": 28.2,
        "Mchc": 32.6,
        "Mcv": 86.5,
        "Limfosit": 31.7,
        "Monosit": 5.2,
        "Neutrofil": 60.1,
        "Neutrofil Limfosit Ratio": 1.90,
        "Rdw-Cv": 14.4,
        "Koles Hdl": 44, // Normal
        "Koles Ldl": 154, // Batas Tinggi
        "Trigliserid": 99, // Normal
        "Sgot": 24, // Normal
        "Sgpt": 25, // Normal
        "Kolesterol": "198 Optima", // Sample: 198 Optima. By rule: 198 < 200 Normal.
        "Ph": 5.5,
        "Warna": "Kuning Pucat",
        "Kejernihan": "Jernih",
        "Leukosit": 0.8,
        "Eritrosit": 2.30,
        "Epitel": 0.50,
        "Bakteri": 131.00,
        "Silinder": 0.00,
        "Kristal": 0.0,
        "Berat Jenis": 1.028,
        "Protein": "Negatif",
        "Glukosa": "Negatif",
        "Keton": "Negatif",
        "Darah": "Negatif",
        "Bilirubin": "Negatif",
        "Urobilinogen": "Normal",
        "Nitrit": "Negatif",
        "Lekosit Esteras": "Negatif",
        "Rasio Albumin Kreatinin": "< 30",
        "Laboratorium": "Kolesterol Total 198 mg/dL, Kolesterol LDL 154 mg/dL, Trigliserida 99 mg/dL",
        "Pemeriksaan Hepatitis": null,
        "Audiometri": null,
        "Radiologi": "Cor, pulmo, sinus",
        "Fisik": "BMI: Obese I",
        "Visus": " Mata Kanan : 6/6, Mata Kiri : 6/6",
        "Buta Warna": "Tidak",
        "Saran": "Fisik : ---, EKG : null, Visus : ---, Laboratorium : Edukasi pola hidup sehat (diet rendah lemak jenuh, olahraga teratur), Audiometri : null, Rontgen Thorax : ---, Buta Warna : ---"
    },
     {
        "NO.": 8,
        "TANGGAL": "18/05/2025 08:43",
        "NO REG": 2505030643,
        "NO RM": 2301759,
        "NAMA PASIEN": "Citra Mahara",
        "Jenis Kelamin": "Perempuan",
        "Usia": 26, // <35
        "Tgl Lahir": "04/05/1999",
        "Unit Kerja": "Radiologi", // Shortened Unit Kerja? Handle variations?
        "Jabatan": "Pelaksana",
        "Ketenagaan": "Tenaga Non", // Missing "Kesehatan"?
        "Tanggal Periksa": "10/04/2025",
        "BB\n(Kg)": 60,
        "TB\n(Cm)": 160,
        "IMT": 23.44,
        "Kategori IMT": "Normal",
        "TD": "90/57",
        "Kategori TD": "Optimal", // S=90, D=57 -> Optimal
        "Riwayat Kesehatan Pribadi": "Riwayat Penyakit : Tidak Ada",
        "Riwayat Kesehatan Keluarga": "Riwayat Penyakit Keluarga : Tidak Ada",
        "Anamnesa": "Anamnesa : Keluhan saat ini : ---",
        "Merokok": "Tidak",
        "Alkohol": "Tidak",
        "Olahraga": "",
        "EKG": "normal",
        "Kreatinin": 0.6, // Normal
        "Egfr": 126,
        "Ureum": 13, // Tidak Normal (<15)
        "Glukosa Puasa": 80.0, // Normal
        "Anti Hbs": "",
        "Hbsag": "",
        "Asam Urat": 4.5, // Normal woman
        "Basofil": 0.4,
        "Eosinofil": 2.2,
        "Hb": 12.9, // Normal woman
        "Hematokrit": 39.4,
        "Trombosit": 212,
        "Eritrosit": 4.17,
        "Lekosit": 4.77,
        "Mch": 30.8,
        "Mchc": 32.6,
        "Mcv": 94.6,
        "Limfosit": 37.7,
        "Monosit": 8.4,
        "Neutrofil": 51.3,
        "Neutrofil Limfosit Ratio": 1.36,
        "Rdw-Cv": 12.8,
        "Koles Hdl": 58, // Normal
        "Koles Ldl": 117, // Hampir Optimal
        "Trigliserid": 48, // Normal
        "Sgot": 22, // Normal
        "Sgpt": 17, // Normal
        "Kolesterol": "179 Optima", // Normal
        "Ph": 7.5,
        "Warna": "Kuning Muda",
        "Kejernihan": "Jernih",
        "Leukosit": 0.1,
        "Eritrosit": 1.60,
        "Epitel": 1.00,
        "Bakteri": 43.50,
        "Silinder": 0.00,
        "Kristal": 0.0,
        "Berat Jenis": 1.009,
        "Protein": "Negatif",
        "Glukosa": "Negatif",
        "Keton": "Negatif",
        "Darah": "Negatif",
        "Bilirubin": "Negatif",
        "Urobilinogen": "Normal",
        "Nitrit": "Negatif",
        "Lekosit Esteras": "Negatif",
        "Rasio Albumin Kreatinin": "< 30",
        "Laboratorium": "Kolesterol Total 179 mg/dL, Kolesterol LDL 117 mg/dL, Trigliserida 48 mg/dL, Ureum 13 mg/dL",
        "Pemeriksaan Hepatitis": null,
        "Audiometri": null,
        "Radiologi": "Cor, pulmo, sinus",
        "Fisik": "BMI : Normal",
        "Visus": " Mata Kanan : 6/6, Mata Kiri : 6/6",
        "Buta Warna": "Tidak",
        "Saran": "Fisik : ---, EKG : null, Visus : ---, Laboratorium : Konsul dr. Sp. PD (untuk Ureum yang rendah), Audiometri : null, Rontgen Thorax : ---, Buta Warna : ---"
    },
    {
        "NO.": 9,
        "TANGGAL": "18/05/2025 09:23",
        "NO REG": 2505030741,
        "NO RM": 9056712,
        "NAMA PASIEN": "Fitriani Nurha",
        "Jenis Kelamin": "Perempuan",
        "Usia": 38, // >=35
        "Tgl Lahir": "27/09/1986",
        "Unit Kerja": "Pemilihan", // Unusual Unit Kerja?
        "Jabatan": "Pemilihan Radiografer", // Unusual Jabatan?
        "Ketenagaan": "Kesehatan", // Missing "Tenaga"?
        "Tanggal Periksa": "10/04/2025",
        "BB\n(Kg)": 62,
        "TB\n(Cm)": 167,
        "IMT": 22.23,
        "Kategori IMT": "Normal",
        "TD": "126/60",
        "Kategori TD": "Normal", // S=126, D=60 -> Normal
        "Riwayat Kesehatan Pribadi": "Riwayat Penyakit : Batu Empedu, DM", // DM and Batu Empedu
        "Riwayat Kesehatan Keluarga": "Riwayat Penyakit Keluarga : DM, Hipertensi",
        "Anamnesa": "Anamnesa : Keluhan saat ini : ---",
        "Merokok": "Tidak",
        "Alkohol": "Tidak",
        "Olahraga": "",
        "EKG": "Sinus Rhytm",
        "Kreatinin": 0.7, // Normal
        "Egfr": 95,
        "Ureum": 20, // Normal
        "Glukosa Puasa": 84.0, // Normal
        "Anti Hbs": "",
        "Hbsag": "",
        "Asam Urat": 4.7, // Normal woman
        "Basofil": 0.3,
        "Eosinofil": 2.6,
        "Hb": 13.2, // Normal woman
        "Hematokrit": 40.8,
        "Trombosit": 226,
        "Eritrosit": 4.57,
        "Lekosit": 4.52,
        "Mch": 28.9,
        "Mchc": 32.4,
        "Mcv": 89.4,
        "Limfosit": 31.4,
        "Monosit": 11.1,
        "Neutrofil": 54.6,
        "Neutrofil Limfosit Ratio": 1.74,
        "Rdw-Cv": 13.9,
        "Koles Hdl": 48, // Normal
        "Koles Ldl": 150, // Batas Tinggi
        "Trigliserid": 71, // Normal
        "Sgot": 16, // Normal
        "Sgpt": 13, // Normal
        "Kolesterol": "199 Optima", // Normal
        "Ph": 5.5,
        "Warna": "Kuning Pucat",
        "Kejernihan": "Jernih",
        "Leukosit": 31.3,
        "Eritrosit": 32.20,
        "Epitel": 16.40,
        "Bakteri": 1047.10,
        "Silinder": 0.41,
        "Kristal": 0.0,
        "Berat Jenis": 1.025,
        "Protein": "Negatif",
        "Glukosa": "Negatif",
        "Keton": "Negatif",
        "Darah": "1+", // Sample shows 1+. Need to handle non-Negatif/non-numeric.
        "Bilirubin": "Negatif",
        "Urobilinogen": "Normal",
        "Nitrit": "Negatif",
        "Lekosit Esteras": "1+", // Sample shows 1+. Need to handle non-Negatif/non-numeric.
        "Rasio Albumin Kreatinin": "< 30",
        "Laboratorium": "Kolesterol Total 199 mg/dL, Kolesterol LDL 150 mg/dL, Trigliserida 71 mg/dL",
        "Pemeriksaan Hepatitis": null,
        "Audiometri": null,
        "Radiologi": "Cor, pulmo, sinus",
        "Fisik": "BMI : Normal",
        "Visus": " Mata Kanan : 6/6, Mata Kiri : 6/6",
        "Buta Warna": "Tidak",
        "Saran": "Fisik : ---, EKG : null, Visus : ---, Laboratorium : Edukasi pola hidup sehat (konsumsi makanan rendah lemak jenuh, olahraga teratur), Audiometri : null, Rontgen Thorax : ---, Buta Warna : ---"
    },
     {
        "NO.": 10,
        "TANGGAL": "18/05/2025 09:29",
        "NO REG": 2505030798,
        "NO RM": 4718390,
        "NAMA PASIEN": "Bambang Set",
        "Jenis Kelamin": "Laki-laki",
        "Usia": 30, // <35
        "Tgl Lahir": "01/12/1994",
        "Unit Kerja": "Instalasi Radiologi",
        "Jabatan": "Ahli Madya",
        "Ketenagaan": "Tenaga Kesehatan",
        "Tanggal Periksa": "10/04/2025",
        "BB\n(Kg)": 66,
        "TB\n(Cm)": 158,
        "IMT": 26.44,
        "Kategori IMT": "Overweight",
        "TD": "101/65",
        "Kategori TD": "Optimal", // S=101, D=65 -> Optimal
        "Riwayat Kesehatan Pribadi": "Riwayat Penyakit : Dispepsia, Keluhan Muskoloskeletal", // Dispepsia -> Dyspepsia, Keluhan Muskoloskeletal
        "Riwayat Kesehatan Keluarga": "Riwayat Penyakit Keluarga : Tidak Ada",
        "Anamnesa": "Anamnesa : Keluhan saat ini : ---",
        "Merokok": "Tidak",
        "Alkohol": "Tidak",
        "Olahraga": "",
        "EKG": "Sinus Rhytm",
        "Kreatinin": 0.7, // Normal
        "Egfr": 126,
        "Ureum": 15, // Normal
        "Glukosa Puasa": 89.0, // Normal
        "Anti Hbs": "",
        "Hbsag": "",
        "Asam Urat": 5.5, // Normal man
        "Basofil": 0.6,
        "Eosinofil": 1.1,
        "Hb": 15.9, // Normal man
        "Hematokrit": 48.7,
        "Trombosit": 201,
        "Eritrosit": 5.16,
        "Lekosit": 6.62,
        "Mch": 30.8,
        "Mchc": 32.6,
        "Mcv": 94.4,
        "Limfosit": 34.0,
        "Monosit": 8.0,
        "Neutrofil": 56.3,
        "Neutrofil Limfosit Ratio": 1.66,
        "Rdw-Cv": 13.8,
        "Koles Hdl": 43, // Normal
        "Koles Ldl": 168, // Tinggi
        "Trigliserid": 183, // Batas Tinggi
        "Sgot": 26, // Normal
        "Sgpt": 31, // Normal
        "Kolesterol": "228 Borderlir", // Sample typo "Borderlir". Let's assume "Borderline". Value 228 is Batas Tinggi.
        "Ph": 6.0,
        "Warna": "Kuning Pucat",
        "Kejernihan": "Jernih",
        "Leukosit": 1.6,
        "Eritrosit": 17.30,
        "Epitel": 0.20,
        "Bakteri": 4.40,
        "Silinder": 0.13,
        "Kristal": 0.0,
        "Berat Jenis": 1.017,
        "Protein": "Negatif",
        "Glukosa": "Negatif",
        "Keton": "Negatif",
        "Darah": "+-", // Sample shows +-. Need to handle non-Negatif.
        "Bilirubin": "Negatif",
        "Urobilinogen": "Normal",
        "Nitrit": "Negatif",
        "Lekosit Esteras": "Negatif",
        "Rasio Albumin Kreatinin": "< 30",
        "Laboratorium": "Kolesterol Total 228 mg/dL, Kolesterol LDL 168 mg/dL, Trigliserida 183 mg/dL",
        "Pemeriksaan Hepatitis": null,
        "Audiometri": null,
        "Radiologi": "Radiografi thorax",
        "Fisik": "BMI : Overweight",
        "Visus": " Mata Kanan : 6/6, Mata Kiri : 6/6",
        "Buta Warna": "Tidak",
        "Saran": "Fisik : ---, EKG : null, Visus : ---, Laboratorium : Edukasi pola hidup sehat (diet rendah lemak jenuh, olahraga teratur), Audiometri : null, Rontgen Thorax : ---, Buta Warna : ---"
    }
    // Add more mock data as needed to test other categories
    // Example for elevated Glukosa Puasa:
    , {
         "NO.": 11,
         "TANGGAL": "19/05/2025 10:00",
         "NO REG": 2505030888,
         "NO RM": 1122334,
         "NAMA PASIEN": "Pasien Gula Tinggi",
         "Jenis Kelamin": "Laki-laki",
         "Usia": 50,
         "Tgl Lahir": "01/01/1975",
         "Unit Kerja": "Internal",
         "Jabatan": "Manajer",
         "Ketenagaan": "Tenaga Kesehatan",
         "Tanggal Periksa": "11/04/2025",
         "BB\n(Kg)": 80,
         "TB\n(Cm)": 170,
         "IMT": 27.68,
         "Kategori IMT": "Overweight",
         "TD": "145/95", // Hipertensi I
         "Kategori TD": null,
         "Riwayat Kesehatan Pribadi": "Riwayat Penyakit : DM",
         "Riwayat Kesehatan Keluarga": "Riwayat Penyakit Keluarga : Hipertensi",
         "Anamnesa": "Kontrol DM",
         "Merokok": "Ya",
         "Alkohol": "Tidak",
         "Olahraga": "Jarang",
         "EKG": "Normal",
         "Kreatinin": 1.5, // Tidak Normal
         "Egfr": null,
         "Ureum": 50, // Tidak Normal
         "Glukosa Puasa": 180.0, // Peningkatan Glukosa Puasa
         "Anti Hbs": null,
         "Hbsag": null,
         "Asam Urat": 7.5, // Tinggi
         "Basofil": 0.1,
         "Eosinofil": 1.0,
         "Hb": 14.0, // Normal
         "Hematokrit": 42.0,
         "Trombosit": 250,
         "Eritrosit": 4.50,
         "Lekosit": 7.00,
         "Mch": null,
         "Mchc": null,
         "Mcv": null,
         "Limfosit": null,
         "Monosit": null,
         "Neutrofil": null,
         "Neutrofil Limfosit Ratio": null,
         "Rdw-Cv": null,
         "Koles Hdl": 35, // Rendah
         "Koles Ldl": 170, // Tinggi
         "Trigliserid": 250, // Tinggi
         "Sgot": 40, // Normal
         "Sgpt": 60, // Peningkatan (SGPT > 55)
         "Kolesterol": "260 Tinggi", // Tinggi
         "Ph": null,
         "Warna": null,
         "Kejernihan": null,
         "Leukosit": null,
         "Eritrosit": null,
         "Epitel": null,
         "Bakteri": null,
         "Silinder": null,
         "Kristal": null,
         "Berat Jenis": null,
         "Protein": null,
         "Glukosa": null,
         "Keton": null,
         "Darah": null,
         "Bilirubin": null,
         "Urobilinogen": null,
         "Nitrit": null,
         "Lekosit Esteras": null,
         "Rasio Albumin Kreatinin": null,
         "Laboratorium": null,
         "Pemeriksaan Hepatitis": null,
         "Audiometri": null,
         "Radiologi": null,
         "Fisik": null,
         "Visus": null,
         "Buta Warna": null,
         "Saran": null
     },
     // Example for missing data
    {
        "NO.": 12,
        "TANGGAL": "19/05/2025 10:15",
        "NO REG": 2505030999,
        "NO RM": 4455667,
        "NAMA PASIEN": "Pasien Data Missing",
        "Jenis Kelamin": "Perempuan",
        "Usia": null, // Missing age
        "Tgl Lahir": null,
        "Unit Kerja": null,
        "Jabatan": null,
        "Ketenagaan": null,
        "Tanggal Periksa": null,
        "BB\n(Kg)": null,
        "TB\n(Cm)": null,
        "IMT": NaN, // Missing BMI
        "Kategori IMT": null,
        "TD": "", // Missing TD
        "Kategori TD": null,
        "Riwayat Kesehatan Pribadi": null, // Missing Riwayat
        "Riwayat Kesehatan Keluarga": null,
        "Anamnesa": null,
        "Merokok": null,
        "Alkohol": null,
        "Olahraga": null,
        "EKG": null,
        "Kreatinin": null, // Missing Creatinin
        "Egfr": null,
        "Ureum": null, // Missing Ureum
        "Glukosa Puasa": null, // Missing Glukosa
        "Anti Hbs": null,
        "Hbsag": null,
        "Asam Urat": null,
        "Basofil": null,
        "Eosinofil": null,
        "Hb": null, // Missing Hb
        "Hematokrit": null,
        "Trombosit": null,
        "Eritrosit": null,
        "Lekosit": null,
        "Mch": null,
        "Mchc": null,
        "Mcv": null,
        "Limfosit": null,
        "Monosit": null,
        "Neutrofil": null,
        "Neutrofil Limfosit Ratio": null,
        "Rdw-Cv": null,
        "Koles Hdl": null, // Missing HDL
        "Koles Ldl": null, // Missing LDL
        "Trigliserid": null, // Missing Trigliserida
        "Sgot": null, // Missing SGOT
        "Sgpt": null, // Missing SGPT
        "Kolesterol": null, // Missing Kolesterol Total
        "Ph": null,
        "Warna": null,
        "Kejernihan": null,
        "Leukosit": null,
        "Eritrosit": null,
        "Epitel": null,
        "Bakteri": null,
        "Silinder": null,
        "Kristal": null,
        "Berat Jenis": null,
        "Protein": null,
        "Glukosa": null,
        "Keton": null,
        "Darah": null,
        "Bilirubin": null,
        "Urobilinogen": null,
        "Nitrit": null,
        "Lekosit Esteras": null,
        "Rasio Albumin Kreatinin": null,
        "Laboratorium": null,
        "Pemeriksaan Hepatitis": null,
        "Audiometri": null,
        "Radiologi": null,
        "Fisik": null,
        "Visus": null,
        "Buta Warna": null,
        "Saran": null
    }
];